### ISSUE TITLE
Add support for CCC

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-Shop_Chat#3]
Team name display are overwrite by Shop_Chat when CCC is loaded.
Shop_Chat should keep overwrite tag/name/text display of CCC ? (cvar?)

https://github.com/srcdslab/sm-plugin-CustomChatColors

**Comment by maxime1907** [comment]
just make a check to know if the player has enabled shop chat tag/name/text and if so dont process it in customchatcolors
